// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimalCaretakers.Data.Models;

public partial class ToSeePlan
{
    public long Id { get; set; }

    public long RecruiterId { get; set; }

    public long EmployeeId { get; set; }

    public virtual User Employee { get; set; }

    public virtual User Recruiter { get; set; }
}