// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimalCaretakers.Data.Models;

public partial class User
{
    public long Id { get; set; }

    public string GivenName { get; set; }

    public string Surname { get; set; }

    public string Username { get; set; }

    public string Password { get; set; }

    public int UserType { get; set; }

    public int VisitCounter { get; set; }

    public long SensitiveInfoId { get; set; }

    public virtual ICollection<MeetingInvitation> MeetingInvitationEmployees { get; } = new List<MeetingInvitation>();

    public virtual ICollection<MeetingInvitation> MeetingInvitationRecruiters { get; } = new List<MeetingInvitation>();

    public virtual UserSensitiveInfo SensitiveInfo { get; set; }

    public virtual ICollection<ToSeePlan> ToSeePlanEmployees { get; } = new List<ToSeePlan>();

    public virtual ICollection<ToSeePlan> ToSeePlanRecruiters { get; } = new List<ToSeePlan>();
}