// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace AnimalCaretakers.Data.Models;

public partial class UserSensitiveInfo
{
    public long Id { get; set; }

    public string SkillsValue { get; set; }

    public bool SkillsIsPublic { get; set; }

    public string PortfolioValue { get; set; }

    public bool PortfolioIsPublic { get; set; }

    public string SuccesesValue { get; set; }

    public bool SuccesesIsPublic { get; set; }

    public decimal? ExpectedSalaryValue { get; set; }

    public bool ExpectedSalaryIsPublic { get; set; }

    public virtual User User { get; set; }
}