// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AnimalCaretakers.Data;
using AnimalCaretakers.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AnimalCaretakers.Data.Configurations
{
    public partial class ToSeePlanConfiguration : IEntityTypeConfiguration<ToSeePlan>
    {
        public void Configure(EntityTypeBuilder<ToSeePlan> entity)
        {
            entity.HasOne(d => d.Employee).WithMany(p => p.ToSeePlanEmployees)
            .HasForeignKey(d => d.EmployeeId)
            .OnDelete(DeleteBehavior.ClientSetNull);

            entity.HasOne(d => d.Recruiter).WithMany(p => p.ToSeePlanRecruiters)
            .HasForeignKey(d => d.RecruiterId)
            .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<ToSeePlan> entity);
    }
}
