// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AnimalCaretakers.Data;
using AnimalCaretakers.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AnimalCaretakers.Data.Configurations
{
    public partial class UserConfiguration : IEntityTypeConfiguration<User>
    {
        public void Configure(EntityTypeBuilder<User> entity)
        {
            entity.HasIndex(e => e.SensitiveInfoId, "IX_Users_SensitiveInfoId").IsUnique();

            entity.Property(e => e.GivenName).HasMaxLength(60);
            entity.Property(e => e.Password)
            .IsRequired()
            .HasMaxLength(60);
            entity.Property(e => e.Surname).HasMaxLength(60);
            entity.Property(e => e.Username)
            .IsRequired()
            .HasMaxLength(60);

            entity.HasOne(d => d.SensitiveInfo).WithOne(p => p.User)
            .HasForeignKey<User>(d => d.SensitiveInfoId)
            .OnDelete(DeleteBehavior.ClientSetNull);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<User> entity);
    }
}
