// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using AnimalCaretakers.Data;
using AnimalCaretakers.Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;

namespace AnimalCaretakers.Data.Configurations
{
    public partial class UserSensitiveInfoConfiguration : IEntityTypeConfiguration<UserSensitiveInfo>
    {
        public void Configure(EntityTypeBuilder<UserSensitiveInfo> entity)
        {
            entity.Property(e => e.ExpectedSalaryValue).HasPrecision(19, 5);
            entity.Property(e => e.PortfolioValue)
            .IsRequired()
            .HasMaxLength(512);
            entity.Property(e => e.SkillsValue)
            .IsRequired()
            .HasMaxLength(512);
            entity.Property(e => e.SuccesesValue)
            .IsRequired()
            .HasMaxLength(512);

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<UserSensitiveInfo> entity);
    }
}
